# Generated by Django 5.1.5 on 2025-01-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
