# Generated by Django 5.1.6 on 2025-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='highlighted',
            field=models.TextField(default=1),
        ),
    ]
